primevideo/GestionSeries/urls.py
from django.urls import path, re_path
from django.contrib import admin
from moduloSeries import views
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.SerieListView, name='serie-list'),
    path('agregarserie/', views.agregar_serie, name='agregarserie'),
    path('<int:id>/', views.serie_detail, name='serie-detail'),
    path('editar/<int:id>/', views.editar_serie, name='editar-serie'),
    path('eliminar/<int:id>/', views.eliminar_serie, name='eliminar-serie'),
    path('gestionseries/', views.SerieListCrud, name='gestion_series'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



primevideo/moduloSeries/models.py
from django.db import models
 


class Serie(models.Model):

    GENERO_CHOICES = [
        ('Accion', 'Acción'),
        ('Comedia', 'Comedia'),
        ('Drama', 'Drama'),
        ('Suspenso', 'Suspenso'),
        ('Crimen', 'Crimen'),
        ('Romance', 'Romance'),
        ('Terror', 'Terror'),
        ('Musical', 'Musical'),

    ]

    CLASIFICACION_CHOICES = [
        ('TE', 'TE'),
        ('TE+7', 'TE+7'),
        ('14+', '14+'),
        ('18+', '18+'),
    ]

    nombre = models.CharField(max_length=50, help_text='Nombre de la película')
    genero = models.CharField(max_length=20, choices=GENERO_CHOICES,
                              help_text='Género de la película', blank=False)
    clasificacion = models.CharField(
        max_length=8, choices=CLASIFICACION_CHOICES, help_text='Clasificación de la película', blank=False)
    episodio = models.PositiveIntegerField(
        help_text='Cantidad de episodios')
    resena = models.TextField(
        blank=True, help_text='Breve reseña del contenido de la película')
    anio = models.PositiveIntegerField(help_text='Año de lanzamiento' )
    imagen = models.ImageField(upload_to='series/')

    def __str__(self):
        return self.nombre

primevideo/moduloSeries/forms.py
from django import forms
from .models import Serie
from datetime import date


class SerieForm(forms.ModelForm):
    class Meta:
        model = Serie
        fields = ['nombre', 'genero', 'clasificacion', 'episodio', 'resena',
                  'anio','imagen']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la serie'}),
            'genero': forms.Select(attrs={'class': 'form-control'}),
            'clasificacion': forms.Select(attrs={'class': 'form-control'}),
            'episodio': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad de episodios'}),
            'resena': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Breve reseña del contenido de la serie'}),
            'anio': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Año de lanzamiento'}),
            'imagen': forms.ClearableFileInput(attrs={'accept': 'image/*', 'directory': 'series'}), }



primevideo/moduloSeries/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Serie
from .forms import SerieForm
from django.contrib import messages


def SerieListView(request):

    series = Serie.objects.all()

    series = series.order_by('nombre')

    series = {"series":series}

    return render(request,"series_list.html",series)

def SerieListCrud(request):

    series = Serie.objects.all()

    series = series.order_by('nombre')

    series = {"series":series}

    return render(request,"series_crud.html",series)

def serie_detail(request, id):
    serie = get_object_or_404(Serie, id=id)
    return render(request, "serie_details.html", {'serie': serie})


def agregar_serie(request):
    if request.method == 'POST':
        form = SerieForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            # Redirige a la vista lista_articulos
            return SerieListView(request)
    else:
        form = SerieForm()

    return render(request, "serie_form.html", {'form': form})

def eliminar_serie(request, id):
    serie = Serie.objects.get(id=id)
    serie.delete()
    # Agrega un mensaje de confirmación
    messages.success(
        request, f'Se ha eliminado a {serie.nombre}')
    return redirect('serie-list')

def editar_serie(request, id):
    serie = get_object_or_404(Serie, id=id)
    if request.method == 'POST':
        form = SerieForm(request.POST, request.FILES, instance=serie)
        if form.is_valid():
            form.save()
            print("Formulario válido. Serie guardada.")
            return redirect('serie-list')
        else:
            print("Formulario no válido. Errores:", form.errors)
    else:
        form = SerieForm(instance=serie)

    return render(request, 'serie_form.html', {'form': form})


primevideo/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
   
    <style>
        /* Fondo de página y estilos generales */
        body {
            background-color: #151515;;
            color: white;
            font-family: Arial, sans-serif;
        }

        /* Estilo para el header */
        header {
            background-color: black;
            color: white;
            padding: 20px;
            text-align: center;
        }

        /* Estilos para la barra de navegación */
        .navbar {
            background-color: black;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
        }

        .nav-link {
            color: white !important;
            margin-right: 15px;
        }

        .nav-link:hover {
            color: #ffffff !important;
        }

        /* Estilo para las tarjetas */
        .card {
            background-color: #2e2e2e;
            margin: 15px;
            border: none;
            border-radius: 10px;
            transition: transform 0.3s;
        }

        .card:hover {
            transform: scale(1.05);
        }

        .card-img-top {
            height: 300px;
            object-fit: cover;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }

        .card-body {
            color: #e5e5e5;
            text-align: center;
        }

        /* Responsividad para dispositivos */
        @media (max-width: 768px) {
            .card-img-top {
                height: 200px;
            }

            .navbar-brand {
                font-size: 1.3rem;
            }
        }


    </style>
    <title>{% block title %}Prime Video |Ver series{% endblock %}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'serie-list' %}" >primevideo</a>
            <button  class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'serie-list' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'agregarserie' %}">Nueva Serie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gestion_series' %}">Gestión de Series</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <main class="my-4">
            {% block content %}{% endblock %}
        </main>
    </div>

    <!-- Scripts de Bootstrap y jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

primevideo/templates/serie_details.html
<!-- templates/pelicula_detail.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2 class="mb-4" style="color: white;">Detalle de Serie: {{ serie.nombre }}</h2>

    <div class="card" style="width: 600px;">
        <div class="card-body">
            {% if serie.imagen %}
            <img src="{{ serie.imagen.url }}" alt="{{ serie.nombre }}" class="img-fluid mb-4"
                style="width: 300px;">
            {% else %}
            <p class="mb-4">No hay imagen disponible.</p>
            {% endif %}
            <p class="card-text"><strong>Género:</strong> {{ serie.get_genero_display }}</p>
            <p class="card-text"><strong>Clasificación:</strong> {{ serie.get_clasificacion_display }}</p>
            <p class="card-text"><strong>Episodios:</strong> {{ serie.episodio }}</p>
            <p class="card-text"><strong>Reseña:</strong> {{ serie.resena }}</p>
            <p class="card-text"><strong>Año:</strong> {{ serie.anio}}</p>
        </div>
    </div>

    <div class="container mt-5">
        <a href="{% url 'editar-serie' id=serie.id %}" class="btn btn-warning">Editar</a>
        <a href="{% url 'eliminar-serie' id=serie.id %}" class="btn btn-danger"
            onclick="return confirm('¿Estás seguro de que deseas eliminar a {{ serie.nombre }}?')">Eliminar</a>
       
        <a href="{% url 'serie-list' %}" class="btn btn-primary">Volver al Listado de Series</a>
    </div>
</div>

<style>
    /* Ajustes del contenedor principal */
    body {
        background-color: #0f0f12;
        color: #e5e5e5;
        font-family: Arial, sans-serif;
    }

    /* Título */
    h2 {
        font-weight: bold;
        color: #ffffff;
        border-bottom: 2px solid #0071eb;
        padding-bottom: 10px;
        width: fit-content;
        text-align: left;
    }

    /* Estilos de la tarjeta */
    .card {
        background-color: #1f2a38;
        padding: 20px;
        color: #e5e5e5;
        transition: transform 0.3s ease;
    }

    .card:hover {
        transform: scale(1.02);
    }

    /* Estilo del botón */
    .btn-primary {
        background-color: #0071eb;
        border-color: #0071eb;
    }

    .btn-primary:hover {
        background-color: #005bb5;
        border-color: #005bb5;
    }

    /* Responsividad */
    @media (max-width: 768px) {
        .card {
            padding: 15px;
        }

        h2 {
            font-size: 1.8rem;
        }

        .btn {
            width: 100%;
            margin-top: 10px;
        }
    }
</style>

{% endblock %}




primevideo/templates/serie_form.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5" style="background-color: #1f2a38; border-radius: 5px;">
        <h2 class="mb-4 text-white">{% if form.instance.id %}Editar Serie{% else %}Agregar Nueva Serie{% endif %}</h2>

    <form method="post" enctype="multipart/form-data" class="my-form">

      {% csrf_token %}

      <div class="mb-3">
        <label for="{{ form.nombre.id_for_label }}" class="form-label text-white">Nombre de la serie:</label>
        {{ form.nombre }}
      </div>

      <div class="mb-3">
        <label for="{{ form.genero.id_for_label }}" class="form-label text-white">Género:</label>
        {{ form.genero }}
      </div>

      <div class="mb-3">
        <label for="{{ form.clasificacion.id_for_label }}" class="form-label text-white">Clasificación:</label>
        {{ form.clasificacion }}
      </div>

      <div class="mb-3">
        <label for="{{ form.duracion.id_for_label }}" class="form-label text-white">Episodios:</label>
        {{ form.episodio }}
      </div>

      <div class="mb-3">
        <label for="{{ form.resena.id_for_label }}" class="form-label text-white">Reseña:</label>
        {{ form.resena }}
      </div>

      <div class="mb-3">
        <label for="{{ form.duracion.id_for_label }}" class="form-label text-white">Año:</label>
        {{ form.anio }}
      </div>

      <div class="mb-3">
        <label for="{{ form.imagen.id_for_label }}" class="form-label text-white">Imagen de la serie:</label>
        {{ form.imagen }}
      </div>

      <button type="submit" class="btn btn-primary">Guardar cambios</button>
      <br>
      <a href="{% url 'serie-list' %}" class="btn btn-secondary mt-3">Volver al Listado de Series</a>
      <br>
      <br>

      {% if form.errors %}
        <div class="alert alert-danger mt-3" role="alert">
          <strong class="text-white">Por favor, corrija los siguientes errores en el formulario:</strong>
          <ul class="text-white">
            {% for field, errors in form.errors.items %}
              {% for error in errors %}
                <li>{{ field|title }}: {{ error }}</li>
              {% endfor %}
            {% endfor %}
          </ul>
        </div>
      {% endif %}

    </form>
   
  </div>
  <br><br>
  <style>
    /* Estilos del contenedor principal */
    body {
        background-color: #0f0f12;
        color: #e5e5e5;
        font-family: Arial, sans-serif;
    }

    /* Título del formulario */
    h2 {
        font-weight: bold;
        color: #ffffff;
        border-bottom: 2px solid #0071eb;
        padding-bottom: 10px;
    }

    /* Estilos de los campos de entrada */
    .form-control {
        background-color: #121212;
        border: 1px solid #333;
        color: #ffffff;
    }

    .form-control:focus {
        background-color: #1c1c1e;
        border-color: #0071eb;
        box-shadow: none;
    }

    /* Estilo de los botones */
    .btn-primary {
        background-color: #0071eb;
        border-color: #0071eb;
        font-weight: bold;
    }

    .btn-primary:hover {
        background-color: #005bb5;
        border-color: #005bb5;
    }

    .btn-secondary {
        background-color: #6c757d;
        border-color: #6c757d;
    }

    .btn-secondary:hover {
        background-color: #5a6268;
        border-color: #5a6268;
    }

    /* Estilo de las alertas */
    .alert {
        background-color: #333;
        border-color: #ff4c4c;
        color: #e5e5e5;
    }

    /* Responsividad */
    @media (max-width: 768px) {
        .container {
            padding: 15px;
        }

        h2 {
            font-size: 1.5rem;
        }

        .btn {
            width: 100%;
        }
    }
  </style>
{% endblock %}

primevideo/templates/series_crud.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container mt-5">
    <h2 style="color: white;">Gestion Series</h2>
</div>




<div class="table-responsive" style="background-color: white;">
    <table class="table table-bordered table-striped text-center">
        <thead class="thead-dark">
            <tr>
                <th>Portada</th>
                <th>Nombre</th>
                <th>Género</th>
                <th>Año</th>
                <th>Episodios</th>

                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for serie in series %}
            <tr>
                <td class="align-middle">
                    {% if serie.imagen %}
                    <img src="{{ serie.imagen.url }}" alt="{{ serie.nombre }}"
                        style="max-width: 180px; max-height: 230px;">
                    {% else %}
                    <img src="{% static images/not-found.jpg}" alt="">
                    {% endif %}
                </td>
                <td class="align-middle">{{ serie.nombre }}</td>
                <td class="align-middle">{{ serie.genero }}</td>
                <td class="align-middle">{{ serie.anio }}</td>
                <td class="align-middle">{{ serie.episodio }}</td>


                <td class="align-middle">
                    <a href="{% url 'editar-serie' id=serie.id %}" class="btn btn-warning btn-sm"><i
                            class="fas fa-pencil-alt"></i> </a>
                    <a href="{% url 'eliminar-serie' id=serie.id %}" class="btn btn-danger btn-sm"
                        onclick="return confirm('¿Estás seguro de que deseas eliminar a {{ serie.nombre }}?')"><i
                            class="fas fa-times"></i></a>
                    <a href="{% url 'serie-detail' id=serie.id %}" class="btn btn-info btn-sm"><i
                            class="fas fa-eye"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<style>
    /* Estilo inspirado en el formulario */
    body {
        background-color: #151515;
    }

    h2 {
        font-weight: bold;
    }

    .btn {
        margin: 2px;
    }

    /* Responsividad */
    @media (max-width: 768px) {
        .table-responsive {
            overflow-x: auto;
        }

        th, td {
            font-size: 14px;
        }

        img {
            max-width: 100px;
            max-height: 130px;
        }
    }

    @media (max-width: 576px) {
        th, td {
            display: block;
            text-align: left;
        }
    }
</style>

{% endblock %}

primevideo/templates/series_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style>
  /* Estilos generales */
  body {
    background-color: #151515;
    color: #ffffff;
    font-family: Arial, sans-serif;
  }

  h2 {
    color: #ffffff;
    font-weight: bold;
  }

  /* Contenedor principal */
  .container {
    margin-top: 20px;
  }

  /* Estilo de tarjeta */
  .card {
    background-color: #1f2a38;
    border: none;
    height: 100%;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
    border-radius: 8px;
    overflow: hidden;
  }

  .card:hover {
    transform: scale(1.05);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.5);
  }

  .card img {
    max-width: 100%;
    height: 400px;
    object-fit: cover;
  }

  /* Cuerpo de la tarjeta */
  .card-body {
    padding: 15px;
    text-align: center;
  }

  .card-title {
    font-size: 1.1rem;
    color: #ffffff;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    margin-bottom: 8px;
  }

  .card-text {
    font-size: 0.9rem;
    color: #b8c2cc;
    margin: 0;
  }

  /* Botón con margen superior */
  .btn-info {
    background-color: #0071eb;
    color: #ffffff;
    border: none;
    font-weight: bold;
    margin-top: 15px; /* Margen superior para posicionar el botón más abajo */
  }

  .btn-info:hover {
    background-color: #005bb5;
  }

  /* Estilos responsivos */
  @media (max-width: 768px) {
    .container h2 {
      text-align: center;
    }

    .card {
      width: 100%;
      margin: 10px 0;
    }

    .card img {
      height: 300px;
    }
  }
</style>

<div class="container mt-5"><h2 style="color: white;">Series</h2></div>

<div class="row mx-auto">
  {% for serie in series %}
  <div class="col-md-4 mb-4">
    <div class="card mx-auto">
      {% if serie.imagen %}
      <img src="{{ serie.imagen.url }}" class="card-img-top" alt="{{ serie.nombre }}" style="max-height: 100%;">
      {% else %}
      <img src="{% static 'images/not-found.png' %}" class="card-img-top" alt="Sin imagen" style="max-height: 100%;">
      {% endif %}
      <div class="card-body text-center">
        <h5 class="card-title">{{ serie.nombre}}</h5>
        <p class="card-text"><strong>Género:</strong> {{ serie.get_genero_display }}</p>
        <p class="card-text"><strong>Año:</strong> {{ serie.anio}}</p>
        <p class="card-text"><strong>Clasificación:</strong> {{ serie.get_clasificacion_display }}</p>

        <div class="mx-auto ta-c10">
          <a href="{% url 'serie-detail' id=serie.id %}" class="btn btn-info w-100">Ver</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock %}

